---
output:
  pdf_document: default

documentclass: article

classoption:
- 10pt
- a5paper
- onecolumn
- twoside
- notitlepage

fontenc: T1
fontfamily: romande

linestretch: 1.0

geometry:
- inner=2cm
- outer=1cm
- top=2.5cm
- bottom=2.5cm
- headsep=1cm
- headheight=1cm

header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[OR,EL]{`r params$summary`}
- \fancyhead[OL,ER]{`r params$signature`}
- \fancyhead[C]{}
- \renewcommand{\headrulewidth}{0.5pt}
- \fancyfoot[OR,EL]{\thepage}
- \fancyfoot[OL,ER]{}
- \fancyfoot[C]{}
- \renewcommand{\footrulewidth}{0.5pt}
 
- \usepackage{titlesec}
- \titlespacing{\section}{0cm}{0.75cm}{0.75cm}
- \titlespacing{\subsection}{0cm}{0.5cm}{0.5cm}
- \titlespacing{\subsubsection}{0cm}{0.25cm}{0.25cm}

- \usepackage{parskip}
- \setlength{\parskip}{0.5cm}

#- \usepackage{showframe}

author: "Carmen Julia & William"
title: "Pizza"
subtitle: "The healthy way"
params:
  summary: "Healthy pizza"
  signature: "Julia and William"
---

## INGREDIENTS

\vspace{-0.5cm}
\begin{tabbing}
\hspace{2ex} \= \hspace{20ex} \= \hspace{4ex} \= \\
\>                  \>   2 people                \\
\>                  \> \rule{8ex}{0.5pt}         \\
\> - Flour Type 00  \> 300 \> g                  \\
\> - Flour Type 405 \> 200 \> g                  \\
\> - Lukewarm water \> 300 \> mL                 \\
\> - Salt           \> 15  \> g                  \\
\> - Fresh yeast    \> 5   \> g                  \\
\> - Olive oil      \> 35  \> g                  \\
\> - Sauce          \> to your taste             \\
\> - Toppings       \> to your taste             \\
\end{tabbing}
\vspace{-0.5cm}

## KITCHENWARE

\vspace{-0.5cm}
\begin{tabbing}
\hspace{2ex} \= \hspace{19ex} \= \\
\> - Bowl          \> x2         \\
\> - Spoon         \> x1         \\
\> - Plates        \> x2         \\
\> - Kitchen towel \> x1         \\
\> - Oven                        \\
\end{tabbing}
\vspace{-0.5cm}

## PREPARATION

1. Mix flour and salt in a bowl.


2. Prepare 300 ml of lukewarm water. Stir together fresh yeast and about 3-4 tbsp of water until yeast is fully dissolved.


3. Add yeast to the flour and mix well.


4. Gradually add the remaining water, while mixing well to form a soft dough.


5. Knead for about 5 min before adding the olive oil. Add the oil and knead for at least 5-8min until the dough is smooth and elastic.


6. Divide dough in half and roll both parts into balls. Place balls on two separate floured plates and additionally dust with a bit of flour. Cover with plastic wrap or damp kitchen towel.


7. Let dough rise for about 2h. Prepare tomato sauce and pizza toppings in the meantime.


8. Preheat oven to its highest setting (circulating air/Umluft).


9. When the dough has risen, stretch by hand or roll out to form pizza base.


10. Once the oven is heated, precook base for about 6min. Take base out of the oven and add tomato sauce, mozzarella, and toppings of choice. By precooking the base, the crust and the bottom of the base will stay crispy, while the inside of the crust and the top of the base will stay soft and fluffy.


11. Put pizza back into the oven and bake for another 6-10min until the crust is golden brown.

