---
output:
  pdf_document: default

documentclass: article

title: "placeholder"

classoption:
- 11pt
- a5paper
- onecolumn
- twoside

fontenc: T1
fontfamily: romande

linestretch: 1.0

geometry:
- inner=1.5cm
- outer=1cm
- top=2.5cm
- bottom=2.5cm
- headsep=1cm
- footskip=1.25cm
- headheight=1cm

links-as-notes: true

header-includes:
- \renewcommand\maketitle{
    \thispagestyle{firstpage}
      \begin{center}
        \Huge
        \textbf{`r params$title`}
        \par
        \vspace{0.50cm}
        \large
        \textbf{`r params$runningtitle`}
        \par
        \vspace{0.20cm}
        \small
        \textbf{`r params$author`}
        \par
        \vspace{0cm}
        \rule{0.4\textwidth}{0.5pt}
      \end{center}
  }

- \usepackage{fancyhdr}
- \pagestyle{fancy}
    \fancyhead[OR,EL]{`r params$title`}
    \fancyhead[OL,ER]{\rightmark}
    \fancyhead[C]{}
    \fancyfoot[OR,EL]{\thepage}
    \fancyfoot[OL,ER]{`r params$author`}
    \fancyfoot[C]{}
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0pt}
- \fancypagestyle{firstpage}{
    \fancyhead[OR,EL]{}
    \fancyhead[OL,ER]{}
    \fancyhead[C]{}
    \fancyfoot[OR,EL]{\thepage}
    \fancyfoot[OL,ER]{}
    \fancyfoot[C]{}
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0pt}
  }

- \usepackage{titlesec}
- \titlespacing{\section}{0cm}{0.75cm}{0.75cm}
- \titlespacing{\subsection}{0cm}{0.5cm}{0.5cm}
- \titlespacing{\subsubsection}{0cm}{0.25cm}{0.25cm}

- \usepackage{parskip}
- \setlength{\parskip}{0.5cm}

- \usepackage{float}

#- \usepackage{showframe}

